# Generated by Django 4.2.7 on 2023-11-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_veiw_count',
            field=models.IntegerField(default=1),
        ),
    ]
