# Generated by Django 4.2.7 on 2023-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_book_book_name_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(max_length=100),
        ),
    ]
