# Generated by Django 4.2.7 on 2023-11-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_alter_book_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_view_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
