# Generated by Django 4.2.7 on 2023-11-15 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vege', '0012_alter_book_book_description_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='HELLO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='HI', upload_to='book3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.TextField(default='NILL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_view_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
